# Generated by Django 6.1 on 2026-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина, мм'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Толщина, мм'),
        ),
    ]
