# Generated by Django 6.1 on 2026-09-04 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
        ('goods', '0004_product_thicknesses_lengths_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_product',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_session_product',
        ),
        migrations.AddField(
            model_name='cart',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина, мм'),
        ),
        migrations.AddField(
            model_name='cart',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Толщина, мм'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product', 'thickness', 'length'), name='unique_user_product', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_key', 'product', 'thickness', 'length'), name='unique_session_product', nulls_distinct=False),
        ),
    ]
