# Generated by Django 6.1 on 2026-09-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Подзаголовок')),
                ('link', models.CharField(blank=True, max_length=250, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('sort',),
            },
        ),
    ]
