# Generated by Django 6.1 on 2026-09-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='goods/thumbs/', verbose_name='Миниатюра'),
        ),
    ]
