# Generated by Django 6.1 on 2026-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Пустое поле — адрес соберётся из названия автоматически.', max_length=250, unique=True, verbose_name='URL'),
        ),
    ]
